#!/bin/bash

### BEGIN INIT INFO
# Provides:          rna-seqlyze-worker
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: RNA-Seqlyze worker daemon
# Description:       Debian init script for the RNA-Seqlyze worker daemon
### END INIT INFO

# Usage:
#	- configure the four variables below
#       - copy this file to /etc/init.d/rna-seqlyze.sh
#	- enable it with `insserv /etc/init.d/rna-seqlyze.sh`

###

PREFIX=@@PREFIX@@	# the <prefix> passed to `rnas-install`
WORKDIR=@@WORKDIR@@	# the <workdir> passed to `rnas-init`

WORKER_USER=@@WORKER_USER@@
GROUP=@@GROUP@@

###

test -x $PREFIX/bin/rnas-worker || exit 0

export PATH=$PREFIX/bin:/bin:/usr/bin
export PYTHONUSERBASE=$PREFIX

. /lib/lsb/init-functions

case "$1" in
    start|stop)
        log_daemon_msg "${1^} RNA-Seqlyze worker daemon" rna-seqlyze-worker
        /sbin/start-stop-daemon \
                    --chuid $WORKER_USER:$GROUP \
                    --pidfile $WORKDIR/worker-daemon.pid \
                    --startas $PREFIX/bin/rnas-worker --$1 -- $WORKDIR $1
        log_end_msg $?
    ;;
    *)
        echo "Usage: /etc/init.d/rna-seqlyze.sh {start|stop}"
        exit 1
    ;;
esac

exit 0
