#!/usr/bin/env python

top = '.'
out = 'build'

def configure(conf):
        pass

def build(bld):
        v = bld(myattr='Hello, world!')
        v.myattr = 'Hello, world!'
        v.myMethod()

from waflib import TaskGen

@TaskGen.taskgen_method
def myMethod(self):
        print(getattr(self, 'myattr', None))
