#!/usr/bin/env python

top = out = '.'

def configure(cnf):
	pass

def build(bld):

	bld(
		rule="make",
		cwd="SRA_SDK",
		os_env={ "LD_RUN_PATH": bld.top_dir + "/SRA_SDK/linux/pub/gcc/x86_64/lib" }
	)









# don't look! ... (at the gory details :-))

import TaskGen
@TaskGen.feature('*')
@TaskGen.after('process_rule')
def add_os_env(tg):
	print 'add_os_env(', tg.name, ')'
	for task in tg.tasks:
		env = getattr(tg, "os_env", None)
		if env:
			import os
			# task.env.env is usually empty, in which
			# case the command inherits the os.environ
			# if it is not, the command gets that dict
			# as it's os environment, hence copy the os
			# environment variables here to task.env.env
			print ' adding environment variable', env
			env.update(os.environ)
			task.env.env = env
