#!/usr/bin/env python
# encoding: utf-8

top = out = '.'

import os

print os.path.abspath(".")

def configure(cnf):
	print "1:", cnf.top_dir

def build(bld):

	global abstop
	abs_top = bld.top_dir
	bld(rule=sra_sdk_build)

def sra_sdk_build(task):

	top = task.generator.bld.top_dir
	print "LD_RUN_PATH=" + top + "/SRA_SDK/linux/pub/gcc/x86_64/lib" + " make STATIC= STATICSYSLIBS=" + " cwd:" + "SRA_SDK"
